### PR TITLE
6pm 4 fix deprecation in env

### PR DESCRIPTION
**Pull request by jc9907**
Jiachen Zhang, Ian Wu
Created file jsconfig.json and deleted .env file.

### CODE REVIEW

**Review by alonkatzcs — APPROVED** [review]
Looks good!

**Review by zminshall — APPROVED** [review]
LGTM

**Comment by ZechenM** [comment]
LGTM

**Review by andrewhlu — COMMENTED** [review]
Can we remove the `.DS_Store` file that was checked in, and maybe add files with that extension into the `.gitignore` so this doesn't happen going forward?

**Pull request merged**
